spring:
  application:
    name: todo-list-application
    version: 0.0.1
  profiles.active: test

  jackson:
      property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES


---
spring:
  profiles: local

  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf8
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: false
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: none


---
spring:
  profiles: test

  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:todo;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  demo_number_map:
    1: ONE
    2: TWO
    3: THREE
    4: FOUR
    5: FIVE
    6: SIX
    7: SEVEN
    8: EIGHT
    9: NINE
    10: TEN

  configImageURL: http://s3.com/mobile/images.png

  my.secret: ${random.value}
  my.number: ${random.int}
  my.uuid: ${random.uuid}
  my.number.less.than.ten: ${random.int(10)}
  my.number.in.range: ${random.int[1024,65536]}
